version: "3"
services:
  flask:
    build: ./docker/flask
    ports:
      - "5008:5000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./docker/flask/src:/catalogue
      - ./docker/flask/static:/static
      - ./docker/flask/upload:/upload
    environment:
      FLASK_ENV: development
      FLASK_APP: .
  db:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: catalogue
      MYSQL_USER: catalogue
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
