version: "3"
services:
  db:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: catalogue
      MYSQL_USER: catalogue
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  backend:
    build: ./backend
    ports:
      - "5008:5000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - "./backend:/usr/src/app"
      - /static
      - /upload