version: "3"
services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5008:8080"
    links:
      - postgres 
    environment:
      DATABASE_URL: postgres://catalogue:password@postgres:5432/catalogue
  postgres:
    image: "postgres"
    restart: unless-stopped
    environment:
      POSTGRES_USER: catalogue
      POSTGRES_PASSWORD: password
  vue:
    build: ./vue
    restart: unless-stopped
    ports:
      - "8080:8080"
