version: "3"
services:
  flask:
    image: ghcr.io/charmk-code/catalogue_flask:latest
    restart: unless-stopped
    ports:
      - "5008:5000"
    depends_on:
      flyway:
        condition: service_completed_successfully
    links:
      - db
    volumes:
      - ./docker/flask/src:/catalogue
      - /static
      - /upload
    environment:
      FLASK_ENV: production
      FLASK_APP: .
      SERVER_MODE: summer job
  flyway:
    image: flyway/flyway
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./flyway:/flyway/sql
    command: -url=jdbc:mysql://db:3306/catalogue -user=catalogue -password=password -connectRetries=60 migrate
  db:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: catalogue
      MYSQL_USER: catalogue
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  vue:
    image: ghcr.io/charmk-code/catalogue_vue:latest
    restart: unless-stopped
    ports:
      - "8080:3000"
