#!/bin/bash
dir=$(pwd)
docker run \
                                  --rm \
                                  -e SONAR_HOST_URL="http://77.107.46.93:9000" \
                                  -e SONAR_LOGIN=${SONAR_TOKEN} \
  -v "${dir}:/usr/src" \
  --network=host\
                                  sonarsource/sonar-scanner-cli

