FROM python:3

WORKDIR /catalogue

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flask-cors --upgrade

COPY src/ /catalogue

CMD [ "flask", "run", "--host=0.0.0.0"]
