[creds]
password = "password"
secret = ""

[flask]
secret_key = ""
upload_folder = "/upload"
static_folder = "/static"

[database]
user = "catalogue"
pass = "password"
db = "catalogue"
server = "db"
port = "3306"
