# Configuration of the service
[creds]
password = "password"
secret = "adasdjasofhsgfalsöduas öfoyasl312312"

[flask]
secret_key = "9OLWxND4o83j4K4iuopO"
upload_folder = "/uploads"

[database]
# The user and the db need to be created beforehandc (add it in the docker-compose)
user = "catalogue"
pass = "password"
db = "catalogue"

server = "db"
port = "3306"
