name: Docker Image CI

on: 
  push:
    branches:
      - master
      - beta

jobs:
  build-backend:
    runs-on: self-hosted

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
        id: extract_branch

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      # Create latest vesion
      - name: Build the Docker image
        run: docker build backend/ --file backend/Dockerfile --tag ghcr.io/charmk-code/catalogue_backend:latest --tag ghcr.io/charmk-code/catalogue_backend:$BRANCH_NAME
      # push latest version
      - name: Push the Docker image
        run: docker push ghcr.io/charmk-code/catalogue_backend -a

  build-frontend:
    runs-on: self-hosted

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
        id: extract_branch

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2

      # Create latested vesion
      - name: Build the Docker image
        run: docker build vue/ --tag ghcr.io/charmk-code/catalogue_vue:latest --tag ghcr.io/charmk-code/catalogue_vue:$BRANCH_NAME
      - name: Push the Docker image
        run: docker push ghcr.io/charmk-code/catalogue_vue -a 
