name: Docker Image CI

on: 
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: self-hosted

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2

      # Create latested vesion
      - name: Build the latest Docker image
        run: docker build --file backend/Dockerfile --tag ghcr.io/charmk-code/catalogue_backend:latest backend/
      - name: Push the latest Docker image
        run: docker push ghcr.io/charmk-code/catalogue_backend:latest

  build-frontend:
    runs-on: self-hosted

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2

      # Create latested vesion
      - name: Build the latest Docker image
        run: docker build vue/ --tag ghcr.io/charmk-code/catalogue_vue:latest vue/
      - name: Push the latest Docker image
        run: docker push ghcr.io/charmk-code/catalogue_vue:latest
